"""Context management constants."""

SINGLE_RESULT_LIMIT = 50_000
MESSAGE_AGGREGATE_LIMIT = 200_000
SUMMARY_RESERVE = 20_000
AUTO_SAFETY_MARGIN = 13_000
MANUAL_SAFETY_MARGIN = 3_000
RECOVERY_FILE_LIMIT = 5
RECOVERY_TOKENS_PER_FILE = 5_000
RECENT_KEEP_TOKENS = 10_000
RECENT_KEEP_MESSAGES = 5
MAX_CONSECUTIVE_AUTO_COMPACT_FAILURES = 3
PTL_RETRY_LIMIT = 3
PTL_DROP_PERCENTAGE = 0.2
ESTIMATE_CHARS_PER_TOKEN = 3.5
PREVIEW_HEAD_BYTES = 2048
PREVIEW_HEAD_LINES = 20


def auto_compact_threshold(context_window: int) -> int:
    return context_window - SUMMARY_RESERVE - AUTO_SAFETY_MARGIN


# 兼容旧测试/扩展；运行时阈值必须调用 auto_compact_threshold(context_window)。
AUTO_COMPACT_TRIGGER_TOKENS = auto_compact_threshold(200_000)
